apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: drkiq
  name: drkiq
spec:
  type: LoadBalancer
  ports:
  - name: "8000"
    nodePort: 32656
    port: 8000
    targetPort: 8000
  selector:
    io.kompose.service: drkiq
status:
  loadBalancer: {}
