kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume-3
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/postgresql/data"
